Rewarding/Rewarding/Models/TempChange.cs
using Rewarding.Models;
using System.Collections.Generic;
using System.Linq;

namespace Rewarding.Models
{
    public class TempChange
    {
        public List<TempData> changesCollection = new List<TempData>();
        
        public void AddItem(IEntity entity, string method)
        {
            changesCollection.Add(new TempData
                                {
                                    Entity = entity,
                                    Method = method
                                });
        }

        //public void Clear()
        //{
        //    changesCollection.Remove();
        //}

        public IEnumerable<TempData> Lines
        {
            get { return changesCollection; }
        }
    }

    public class TempData
    {
        public IEntity Entity { get; set; }
        public string Method { get; set; }
    }

}

Rewarding/Rewarding/Controllers/TempChangesController.cs
using Rewarding.Controllers;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
//using GameStore.Domain.Entities;
//using GameStore.Domain.Abstract;
//using GameStore.WebUI.Models;

namespace Rewarding.Models
{
    public class TempChangesController : SessionController
    {
        public RedirectToRouteResult ShowChanges(string returnUrl)
        {
            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new TempChangesVM
            {
                TempChange = GetTempChange(),
                ReturnUrl = returnUrl
            });
        }

        private PersonContext db = new PersonContext();
        public RedirectToRouteResult ApplyChanges()
        {
            var data = GetTempChange().changesCollection;

            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    foreach (var item in data)
                    {
                        switch (item.Method)
                        {
                            case "Create":
                                CreateTable(item.Entity);
                                break;
                            case "Edit":
                                EditTable(item.Entity);
                                break;
                            case "Delete":
                                DeleteTable(item.Entity);
                                break;
                        }
                    }
                    db.SaveChanges();
                    RemoveFromTempChanges("");
                    transaction.Commit();
                }
                catch (System.Exception e )
                {
                    transaction.Rollback();
                    ViewBag.ResultMessage = "Error occured, records rolledback.";
                }
                
            }
            return RedirectToAction("Index","Person");
        }

        private void CreateTable(IEntity table)
        {
            if (table.GetType().Name == "Reward")
            {
                Reward reward = (Reward)(table);
                db.Rewards.Add(reward);
            }
            else
            {
                Person person = (Person)(table);
                db.Persons.Add(person);
            }
        }

        private void DeleteTable(IEntity table)
        {
            if (table.GetType().Name.Contains("Reward"))
            {
                Reward reward = db.Rewards.Find(((Reward)(table)).Id);
                Image image = db.Pictures.SingleOrDefault(d => d.ImageId == reward.ImageId);
                db.Rewards.Remove(reward);
                if (image != null)
                {
                    db.Pictures.Remove(image);
                }
            }
            else
            {
                Person person = db.Persons.Find(((Person)(table)).Id);
                Image image = db.Pictures.SingleOrDefault(d => d.ImageId == person.PhotoId);
                db.Persons.Remove(person);
                if (image != null)
                {
                    db.Pictures.Remove(image);
                }
            }
        }
        private void EditTable(IEntity table)
        {
            if (table.GetType().Name == "Reward")
            {
                var newReward = (Reward)(table);
                Reward reward = db.Rewards.Find((newReward).Id);
                db.Entry(reward).CurrentValues.SetValues(newReward);
            }
            else
            {
                var newPerson = (Person)(table);
                Person person = db.Persons.Find((newPerson).Id);
                db.Entry(person).CurrentValues.SetValues(newPerson);
            }
        }

        public RedirectToRouteResult DoNotApplyChanges(string returnUrl)
        {
            RemoveFromTempChanges(returnUrl);
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

Rewarding/Rewarding/Views/TempChanges/Index.cshtml
@model Rewarding.Models.TempChangesVM
@using Rewarding.Models
@{
    ViewBag.Title = "Your changes";
}

<h2>Your changes</h2>
<table class="table">
    <thead>
        <tr>
            <th>Entity</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.TempChange.Lines)
        {
            <tr>
                @{
                    string ent = "";
                    if (line.Entity.GetType().Name.Contains("Reward"))
                    {
                        Reward entity = (Reward)(line.Entity);

                        ent = entity.Title + Environment.NewLine
                             + "\t" + (entity.Description ?? " ").Substring(0, Math.Min(1, 30)) + "...";
                    }
                    else
                    {
                        Person entity = (Person)(line.Entity);
                        ent = entity.Name + Environment.NewLine
                             + "\t" + (entity.Age.ToString() ?? " ").Substring(0, Math.Min(1, 30)) + "...";
                    }
                    <td class="text-center">
                        @ent
                    </td>
                }
                <td class="text-center">
                </td>
                <td class="text-left">@line.Method</td>
            </tr>
        }
    </tbody>
</table>

@using (Html.BeginForm("ApplyChanges", "TempChanges"))
{
    <input class="btn btn-sm btn-warning" type="submit" value="Apply Changes" >
}

@using (Html.BeginForm("DoNotApplyChanges", "TempChanges"))
{
    <input class="btn btn-sm btn-warning" type="submit" value="Don't apply   " />
}