Rewarding/Rewarding/Models/Person.cs
using Rewarding.Controllers;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rewarding.Models
{
    [Table("Persons")]
    public class Person: IEntity
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "The field can't be empty")]
        [StringLength(50, ErrorMessage = "The length of the string must be less than 50 characters")]
        public string Name { get; set; }

        [Required(ErrorMessage = "The field can't be empty")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Birthdate { get; set; }

        [Range(0, 150, ErrorMessage = "Invalid age (must be between 0 and 150)")]
        public int Age { get; set; }

        public virtual ICollection<Reward> Rewards { get; set; }
        public Person()
        {
            Rewards = new List<Reward>();
        }

        public int? PhotoId { get; set; }
        [ForeignKey("PhotoId")]
        public Image Photo { get; set; }
    }
}

Rewarding/Rewarding/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rewarding.Models;

namespace Rewarding.Controllers
{
    public class ImagesController : Controller
    {
        private PersonContext db = new PersonContext();

        public FileContentResult GetImage(int imageId)
        {
            Image image = db.Pictures
                .FirstOrDefault(g => g.ImageId == imageId);

            if (image != null)
            {
                return File(image.Content, image.ContentType);
            }
            else
            {
                return null;
            }
        }
        public FileContentResult Delete(int id)
        {
            Image image = db.Pictures.Find(id);
            db.Pictures.Remove(image);
            db.SaveChanges();
            return null;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rewarding/Rewarding/Controllers/PersonController.cs
using System.Linq;
using System.Web.Mvc;
using Rewarding.Models;
using System.Net;
using System.Data.Entity;
using System.Web;
using System;
using Rewarding.Filters;
using System.Web.Caching;
using System.Web.UI;

namespace Rewarding.Controllers
{
    [ExceptionFilter]
    [LoggingFilter]
    [Authorize(Roles = "admin, candidateAdmin")]
    public class PersonController : SessionController
    {
        PersonContext db = new PersonContext();

        // GET: Person
        [OverrideAuthorization, Authorize(Roles = "user")]
        [AllowAnonymous]
        [OutputCache(Duration = 30, Location = OutputCacheLocation.Server, VaryByParam = "*")]
        public ActionResult Index(string name = null)
        {
            var persons = db.Persons.Include(s => s.Photo).Include(i => i.Rewards)
                        .Where(x => name != null ? x.Name.Contains(name) : true).Select(y => y);

            ViewBag.Rewards = db.Rewards.ToList();
            if (Request.IsAjaxRequest())
            {
                return PartialView("_peopleListPartial", persons);
            }
            //to show how ExceptionFilter works
            //throw new Exception();
            return View(persons);   
        }

        //GET
        public ActionResult Create()
        {
            ViewBag.Rewards = db.Rewards.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Birthdate,Age,Rewards")] Person person, int[] selectedRewards, HttpPostedFileBase uploaded)
        {
            ViewBag.Rewards = db.Rewards.ToList();
            if (ModelState.IsValid)
            {
                if (uploaded != null && uploaded.ContentLength > 0)
                {
                    person.Photo = new Image();
                    person.Photo.ImageName = uploaded.FileName;
                    person.Photo.ContentType = uploaded.ContentType;
                    person.Photo.Content = new byte[uploaded.ContentLength];
                    uploaded.InputStream.Read(person.Photo.Content, 0, uploaded.ContentLength);
                }
                if (User.IsInRole("candidateAdmin"))
                {
                    GetTempChange().AddItem(person, "Create");
                }
                else
                {
                    if (selectedRewards != null)
                    {
                        //получаем выбранные rewards
                        foreach (var c in db.Rewards.Where(co => selectedRewards.Contains(co.Id)))
                        {
                            person.Rewards.Add(c);
                        }
                    }
                    db.Persons.Add(person);
                    db.SaveChanges();
                }
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_personSinglePartial", person);
                }
                return RedirectToAction("Index");
            }

            return View(person); //не должно вызываться
        }

        // GET: /Persons/Details/1 
        public ActionResult Details(int? id, string name = null)
        {
            if (id == null && name == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Person person = new Person();

            if (id != null)
                person = db.Persons.Find(id);
            else
                person = db.Persons.Where(x => x.Name == name).OrderBy(y => y.Birthdate).FirstOrDefault();
            

            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: /Persons/Edit/1 
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            ViewBag.Rewards = db.Rewards.ToList();
            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Birthdate,Age")] Person person, int[] selectedRewards, HttpPostedFileBase uploaded)
        {
            if (ModelState.IsValid)
            {
                Person newPerson = db.Persons.Find(person.Id);
                newPerson.Name = person.Name;
                newPerson.Birthdate = person.Birthdate;
                newPerson.Age = person.Age;

                newPerson.Rewards.Clear();
                if (selectedRewards != null)
                {
                    //получаем выбранные rewards
                    foreach (var c in db.Rewards.Where(co => selectedRewards.Contains(co.Id)))
                    {
                        newPerson.Rewards.Add(c);
                    }
                }

                if (uploaded != null && uploaded.ContentLength > 0)
                {
                    newPerson.Photo = new Image();
                    newPerson.Photo.ImageName = uploaded.FileName;
                    newPerson.Photo.ContentType = uploaded.ContentType;
                    newPerson.Photo.Content = new byte[uploaded.ContentLength];
                    uploaded.InputStream.Read(newPerson.Photo.Content, 0, uploaded.ContentLength);
                }
                if (User.IsInRole("candidateAdmin"))
                {
                    GetTempChange().AddItem(person, "Edit");
                }
                else
                {
                    db.Entry(newPerson).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            ViewBag.Rewards = db.Rewards.ToList();
            return View(person);
        }

        //GET: /Persons/Delete/1
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            Person person = db.Persons.Include(s => s.Photo).SingleOrDefault(s => s.Id == id);
            Image photo = db.Pictures.SingleOrDefault(d => d.ImageId == person.PhotoId);
            if (User.IsInRole("candidateAdmin"))
            {
                GetTempChange().AddItem(person, "Delete");
            }
            else
            {
                db.Persons.Remove(person);
                if (photo !=null)
                    db.Pictures.Remove(photo);
                db.SaveChanges();
            }

            if (Request.IsAjaxRequest())
            {
                return Json(new { id });
            }
            return RedirectToAction("Index");
        }

        public FileResult DownloadListOfPeople()
        {
            var list = db.Persons.Include(i => i.Rewards).ToList();

            var listWithRewards = list.Select(i => i.Name + ": " + Environment.NewLine + "   - " + 
                ((i.Rewards.Count>0)?(string.Join(Environment.NewLine + "   - ", i.Rewards.Select(u => u.Title).ToArray()  )) : "No rewards")).ToArray();

            string people = string.Join(Environment.NewLine, listWithRewards);

            return File(new System.Text.UTF8Encoding().GetBytes(people), "text/pcdslain", "People.txt");
            
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Rewarding/Rewarding/Views/Person/Create.cshtml
@using Rewarding.Models
@model Rewarding.Models.Person

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Person/_LayoutPerson.cshtml";
}

@section styles{
    @System.Web.Optimization.Styles.Render("~/Content/css")
}

@section breadcrumps{
    You are here: @Html.MvcSiteMap().SiteMapPath()
}
<h2>Create</h2>

@using (Html.BeginForm("Create", "Person", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rewards, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <table>
                    <tr>
                    @{
                        int cnt = 0;
                        List<Reward> rewards = ViewBag.Rewards;
                        foreach (Reward reward in rewards)
                        {
                            if (cnt++ % 3 == 0)
                            {
                                @:</tr><tr>
                            }
                            @:<td>
                                <input type="checkbox"
                                        name="selectedRewards"
                                        value="@reward.Id"
                                        @(Html.Raw("")) />
                                @:  @reward.Title
                            @:</td>
                        }
                    @:</tr>
                    }
                 </table>
             </div>
         </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                 <input type="file" name="uploaded" id="Photo" />
                 <input type="button" value="Clear" onclick="clearForm('Photo')" class="btn btn-default btn-xs"/>
            </div>
       </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
}

Rewarding/Rewarding/Views/Person/Delete.cshtml
@using Rewarding.Models
@model Rewarding.Models.Person

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Person/_LayoutPerson.cshtml";
}

@section styles{
    @System.Web.Optimization.Styles.Render("~/Content/css")
}

@section breadcrumps{
    You are here: @Html.MvcSiteMap().SiteMapPath()
}
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rewards)
        </dt>

        <dd>
            <ul>
                @foreach (Reward item in Model.Rewards)
                {
                    <li>@item.Title</li>
                }
            </ul>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @if (Model.PhotoId == null)
            {
                <div class="form-control-static">No photo</div>
            }
            else
            {
                <img class="img-thumbnail" width="150" height="150"
                     src="@Url.Action("GetImage", "Images",
                        new {imageId = Model.PhotoId })" />
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
}

Rewarding/Rewarding/Views/Person/Details.cshtml
@using Rewarding.Models
@model Rewarding.Models.Person

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Person/_LayoutPerson.cshtml";
}

@section styles{
    @System.Web.Optimization.Styles.Render("~/Content/css")
}

@section breadcrumps{
    You are here: @Html.MvcSiteMap().SiteMapPath()
}

<h2>Details</h2>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            Rewards
        </dt>
        <dd>
            <ul>
                @foreach (Reward item in Model.Rewards)
                {
                    <li>@item.Title</li>
                }
            </ul>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @if (Model.PhotoId == null)
            {
                <div class="form-control-static">No photo</div>
            }
            else
            {
                <img class="img-thumbnail" width="150" height="150"
                     src="@Url.Action("GetImage", "Images",
                        new {imageId = Model.PhotoId })" />
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
}

Rewarding/Rewarding/Views/Person/Edit.cshtml
@using Rewarding.Models
@model Rewarding.Models.Person

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Person/_LayoutPerson.cshtml";
}

@section styles{
    @System.Web.Optimization.Styles.Render("~/Content/css")
}

@section breadcrumps{
    You are here: @Html.MvcSiteMap().SiteMapPath()
}

<h2>Edit</h2>
@using (Html.BeginForm("Edit", "Person", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Rewards, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <table>
                    <tr>
                    @{
                        int cnt = 0;
                        List<Reward> rewards = ViewBag.Rewards;
                        foreach (Reward reward in rewards)
                        {
                            if (cnt++ % 3 == 0)
                            {
                                @:</tr><tr>
                            }
                            @:<td>
                                <input type="checkbox"
                                        name="selectedRewards"
                                        value="@reward.Id"
                                         @(Model.Rewards.Contains(reward) ? "checked=\"checked\"" : "") />
                                @:  @reward.Title
                            @:</td>
                        }
                    @:</tr>
                    }
                </table>
            </div>
        </div>

        @if (Model.PhotoId != null)
        {
            <div class="form-group">
                <span class="control-label col-md-2"><strong>Current Photo</strong></span>
                <div class="col-md-10">
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Images",
                        new {imageId = Model.PhotoId })" />
                </div>
            </div>
        }
        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="uploaded" id="Photo"/>
                <input type="button" value="Clear" onclick="clearForm('Photo')" class="btn btn-default btn-xs" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
}

Rewarding/Rewarding/Views/Person/Index.cshtml
@using Rewarding.Models
@using Microsoft.AspNet.Identity
@model IEnumerable<Rewarding.Models.Person>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Person/_LayoutPerson.cshtml";
}

@section styles{
    @System.Web.Optimization.Styles.Render("~/Content/css")
}

@section breadcrumps{
    You are here: @Html.MvcSiteMap().SiteMapPath()
}

@*<div id="dialog" title="Basic dialog">
    <p>This is an animated dialog which is useful for displaying information. The dialog window can be moved, resized and closed with the 'x' icon.</p>
</div>*@
@*<button id="opener">Open Dialog</button>*@

<h2>Index</h2>


@Html.Partial("_createPartial", new Person())


<div id="notesList">
    @Html.Partial("_peopleListPartial")
</div>

<a onclick="refresh()" class="btn btn-default">Refresh</a>


<p>
    @Html.ActionLink("Dowload list of people", "DownloadListOfPeople")
</p>

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
}

<script type="text/javascript">
    function refresh() {
        $.ajax({
            url: '@Url.Action("Index")',
            method: "GET",
            success: function (data) {
                $('#notesList').html(data);
            }
        });
    }
</script>

<script type="text/javascript">
    function OnNoteRemove(data, status, request) {
        if (data.error) {
            OnError(request, status, data.error);
            return;
        }
        var noteId = data.id;
        $('tr[data-note-id = ' + noteId + ']').remove();
    }

    function OnError(request, status, error) {
        alert(error);
    }
</script>

Rewarding/Rewarding/Views/Person/_LayoutPerson.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles{
    @RenderSection("styles", false)
}

<h1 style="color:#ff0000">Место для рекламы </h1>

@section breadcrumps{
    @RenderSection("breadcrumps", false)
}

@RenderBody()

@section scripts{
    @RenderSection("scripts", false)
}

Rewarding/Rewarding/Views/Person/_createPartial.cshtml
@using Rewarding.Models
@model Rewarding.Models.Person


@using (Ajax.BeginForm("Create", new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "peopleListBody", InsertionMode = InsertionMode.InsertAfter }))
{
    <h2>Create</h2>

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rewards, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<Reward> rewards = ViewBag.Rewards;
                            foreach (Reward reward in rewards)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                <input type="checkbox"
                                           name="selectedRewards"
                                           value="@reward.Id"
                                           @(Html.Raw("")) />
                                        @:  @reward.Title
                                        @:</td>
                        }
                            @:</tr>
                         }
                </table>
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="uploaded" id="Photo" />
                    <input type="button" value="Clear" onclick="clearForm('Photo')" class="btn btn-default btn-xs" />
                </div>
            </div>
        
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>

}

Rewarding/Rewarding/Views/Person/_personSinglePartial.cshtml
@model Rewarding.Models.Person

<tr  data-note-id="@Model.Id">
    <td>
        @Html.DisplayFor(modelModel => Model.Name)
    </td>
    <td>
        @Html.DisplayFor(modelModel => Model.Birthdate)
    </td>
    <td>
        @Html.DisplayFor(modelModel => Model.Age)
    </td>

    @if (User.Identity.IsAuthenticated)
    {
        <td>
            @{
                foreach (var reward in Model.Rewards)
                {
                    <img class="img-thumbnail" width="50" height="50"
                         src="@Url.Action("GetImage", "Images", new { imageId = reward.ImageId })" id=@reward.ImageId title=@reward.Title />
                                <br />


                                <script>
                        $(function () {
                            var createDialog = function (selector) {
                                $(selector).dialog({
                                    autoOpen: false,
                                    show: {
                                        effect: "blind",
                                        duration: 1000
                                    },
                                    hide: {
                                        effect: "explode",
                                        duration: 1000
                                    }
                                });
                            };

                            createDialog("#@("dialog" + reward.ImageId)");

                            $("#@reward.ImageId").on("click", function () {
                                $("#@("dialog" + reward.ImageId)").dialog("open");
                            });
                        });
                                </script>

                                <div id=@("dialog" + reward.ImageId) title="Basic dialog">
                                    <p>@reward.Description</p>
                                </div>
                }
            }
        </td>
    }

    <td>
        @if (Model.PhotoId == null)
        {
            <div class="form-control-static">No photo</div>
        }
        else
        {
            <img class="img-thumbnail" width="150" height="150"
                 src="@Url.Action("GetImage", "Images",
                        new {imageId = Model.PhotoId })" />
        }
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Details", "Details", new { id = Model.Id }) |
        @*@Html.ActionLink("Delete", "Delete", new { id = Model.Id })*@
        @using (Ajax.BeginForm("Delete", new { }, new AjaxOptions() { Confirm = "Удалить?", HttpMethod = "POST", OnSuccess = "OnNoteRemove", OnFailure = "OnError" }, new { style = "display: inline-block" }))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("Id", Model.Id)
            <input type="submit" value="Delete" class="btn btn-danger" />}
    </td>
</tr>