Rewarding/Rewarding/Models/Reward.cs
using Rewarding.Controllers;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Rewarding.Models
{
    public class Reward: IEntity
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "The field can't be empty")]
        [StringLength(50, ErrorMessage = "The length of the string must be less than 50 characters")]
        [RegularExpression("^[a-zA-Z0-9 -]+$", ErrorMessage = "Characters are not allowed.")]
        public string Title { get; set; }


        [StringLength(250, ErrorMessage = "The length of the string must be less than 250 characters")]
        public string Description { get; set; }

        public virtual ICollection<Person> Persons { get; set; }
        public Reward()
        {
            Persons = new List<Person>();
        }

        //[Required]
        public int? ImageId { get; set; }


        [ForeignKey("ImageId")]
        public Image Image { get; set; }
    }
}

Rewarding/Rewarding/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rewarding.Models;

namespace Rewarding.Controllers
{
    public class ImagesController : Controller
    {
        private PersonContext db = new PersonContext();

        public FileContentResult GetImage(int imageId)
        {
            Image image = db.Pictures
                .FirstOrDefault(g => g.ImageId == imageId);

            if (image != null)
            {
                return File(image.Content, image.ContentType);
            }
            else
            {
                return null;
            }
        }
        public FileContentResult Delete(int id)
        {
            Image image = db.Pictures.Find(id);
            db.Pictures.Remove(image);
            db.SaveChanges();
            return null;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rewarding/Rewarding/Controllers/RewardsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Rewarding.Models;
using System.Web;
using MvcSiteMapProvider;
using Rewarding.Filters;

namespace Rewarding.Controllers
{
    [LoggingFilter]
    [Authorize(Roles = "admin, candidateAdmin")]
    public class RewardsController : SessionController
    {
        private PersonContext db = new PersonContext();

        // GET: Rewards
        [Route("awards/{name?}")]
        public ActionResult Index(string name = null)
        {
            var rewards = db.Rewards.Include(i => i.Image)
                        .Where(x => name != null ? x.Title.Contains(name) : true).Select(y => y)
                        .ToList();
            if (Request.IsAjaxRequest())
            {
                return PartialView("_rewardsListPartial", rewards);
            }
            return View(rewards);
        }

        // GET: Rewards/Details/5
        [Route("award/{id:int}")]
        [Route("award/{name}")]
        public ActionResult Details(int? id, string name = null)
        {
            if (id == null && name == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Reward reward = new Reward();

            if (id != null)
                reward = db.Rewards.Find(id);
            else
                reward = db.Rewards.Where(x => x.Title == name).FirstOrDefault();

            if (reward == null)
            {
                return HttpNotFound();
            }
            return View(reward);
        }

        // GET: Rewards/Create
        [Route("create-award")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rewards/Create
        [Route("create-award")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Description")] Reward reward,  HttpPostedFileBase uploaded)
        {
            if (ModelState.IsValid)
            {
                if (uploaded != null && uploaded.ContentLength > 0)
                {
                    reward.Image = new Image();
                    reward.Image.ImageName = uploaded.FileName;
                    reward.Image.ContentType = uploaded.ContentType;
                    reward.Image.Content = new byte[uploaded.ContentLength];
                    uploaded.InputStream.Read(reward.Image.Content, 0, uploaded.ContentLength);
                }
                if (User.IsInRole("candidateAdmin"))
                {
                    GetTempChange().AddItem(reward, "Create");
                }
                else
                {
                    db.Rewards.Add(reward);
                    db.SaveChanges();
                }

                if (Request.IsAjaxRequest())
                {
                    return PartialView("_rewardSinglePartial", reward);
                }
                return RedirectToAction("Index");
            }

            return View(reward);
        }

        // GET: Rewards/Edit/5
        [Route("award/{id:int}/edit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reward reward = db.Rewards.Find(id);
            if (reward == null)
            {
                return HttpNotFound();
            }
            return View(reward);
        }

        // POST: Rewards/Edit/5
        [Route("award/{id:int}/edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description")] Reward reward,  HttpPostedFileBase uploaded)
        {
            if (ModelState.IsValid)
            {
                Reward newReward = db.Rewards.Find(reward.Id);
                newReward.Description = reward.Description;
                newReward.Title = reward.Title;

                if (uploaded != null && uploaded.ContentLength > 0)
                {
                    newReward.Image = new Image();
                    newReward.Image.ImageName = uploaded.FileName;
                    newReward.Image.ContentType = uploaded.ContentType;
                    newReward.Image.Content = new byte[uploaded.ContentLength];
                    uploaded.InputStream.Read(newReward.Image.Content, 0, uploaded.ContentLength);
                }
                if (User.IsInRole("candidateAdmin"))
                {
                    GetTempChange().AddItem(reward, "Edit");
                }
                else
                {
                    db.Entry(newReward).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View(reward);
        }

        // GET: Rewards/Delete/5
        [Route("award/{id:int}/delete")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Reward reward = db.Rewards.Find(id);
            if (reward.Persons.Any())
            {
                ViewBag.Message = "You can't delete the reward. It's used in another table";
                return View("DeleteFailure");
            }
            else
            {
                if (reward == null)
                {
                    return HttpNotFound();
                }
                return View(reward);
            }
        }

        // POST: Rewards/Delete/5
        //[Route("award/{id:int}/delete")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reward reward = db.Rewards.Find(id);
            Image image = db.Pictures.SingleOrDefault(d => d.ImageId == reward.ImageId);

            if (User.IsInRole("candidateAdmin"))
            {
                GetTempChange().AddItem(reward, "Delete");
            }
            else
            {
                db.Rewards.Remove(reward);
                if (image!=null)
                {
                    db.Pictures.Remove(image);
                }
                db.SaveChanges();
            }
            if (Request.IsAjaxRequest())
            {
                return Json(new { id });
            }
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rewarding/Rewarding/Views/Rewards/Create.cshtml
@model Rewarding.Models.Reward

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Rewards/_LayoutRewards.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Rewards", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reward</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="uploaded" id="Image"/>
                <input type="button" value="Clear" onclick="clearForm('Image')" class="btn btn-default btn-xs" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Rewarding/Rewarding/Views/Rewards/Delete.cshtml
@model Rewarding.Models.Reward

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Rewards/_LayoutRewards.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reward</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @if (Model.ImageId == null)
            {
                <div class="form-control-static">No image</div>
            }
            else
            {
                <img class="img-thumbnail" width="150" height="150"
                     src="@Url.Action("GetImage", "Images",
                        new {imageId = Model.ImageId })" />
            }
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Rewarding/Rewarding/Views/Rewards/DeleteFailure.cshtml
@{
    ViewBag.Title = "DeleteFailure";
    Layout = "~/Views/Rewards/_LayoutRewards.cshtml";
}

<h2>DeleteFailure</h2>

<h3>@ViewBag.Message</h3>
<div>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Rewarding/Rewarding/Views/Rewards/Details.cshtml
@model Rewarding.Models.Reward

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Rewards/_LayoutRewards.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Reward</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @if (Model.ImageId == null)
            {
                <div class="form-control-static">No image</div>
            }
            else
            {
                <img class="img-thumbnail" width="150" height="150"
                     src="@Url.Action("GetImage", "Images",
                        new {imageId = Model.ImageId })" />
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Rewarding/Rewarding/Views/Rewards/Edit.cshtml
@model Rewarding.Models.Reward

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Rewards/_LayoutRewards.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Rewards", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reward</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.ImageId != null)
        {
            <div class="form-group">
                <span class="control-label col-md-2"><strong>Current Image</strong></span>
                <div class="col-md-10">
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Images",
                        new {imageId = Model.ImageId })" />
                </div>
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="uploaded" id="Image"/>
                <input type="button" value="Clear" onclick="clearForm('Image')" class="btn btn-default btn-xs" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Rewarding/Rewarding/Views/Rewards/Index.cshtml
@using Rewarding.Models
@using Microsoft.AspNet.Identity
@model IEnumerable<Rewarding.Models.Reward>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Rewards/_LayoutRewards.cshtml";
}

<h2>Index</h2>

@Html.Partial("_createPartial", new Reward())

<div id="notesList">
    @Html.Partial("_rewardsListPartial")
</div>
<a onclick="refresh()" class="btn btn-default">Refresh</a>

<script type="text/javascript">
    function refresh() {
        $.ajax({
            url: '@Url.Action("Index")',
            method: "GET",
            success: function (data) {
                $('#notesList').html(data);
            }
        });
    }
</script>

<script type="text/javascript">
    function OnNoteRemove(data, status, request) {
        if (data.error) {
            OnError(request, status, data.error);
            return;
        }
        var noteId = data.id;
        $('tr[data-note-id = ' + noteId + ']').remove();
    }

    function OnError(request, status, error) {
        alert(error);
    }
</script>

Rewarding/Rewarding/Views/Rewards/_LayoutRewards.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles{
    @System.Web.Optimization.Styles.Render("~/Content/css")
}

<h1 style="color:#00ff00">Место для рекламы </h1>

@section breadcrumps{
    You are here: @Html.MvcSiteMap().SiteMapPath()
}

@RenderBody()

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
}

Rewarding/Rewarding/Views/Rewards/_createPartial.cshtml
@using Rewarding.Models
@model Rewarding.Models.Reward

@using (Ajax.BeginForm("Create", new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "rewardsListBody", InsertionMode = InsertionMode.InsertAfter }))
{
    <h2>Create</h2>

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Reward</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="uploaded" id="Image" />
                <input type="button" value="Clear" onclick="clearForm('Image')" class="btn btn-default btn-xs" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Rewarding/Rewarding/Views/Rewards/_rewardSinglePartial.cshtml
@model Rewarding.Models.Reward

<tr  data-note-id="@Model.Id">
    <td>
        @Html.DisplayFor(modelModel => Model.Title)
    </td>
    <td>
        @Html.DisplayFor(modelModel => Model.Description)
    </td>
    <td>
        @if (Model.ImageId == null)
        {
            <div class="form-control-static">No image</div>
        }
        else
        {
            <img class="img-thumbnail" width="150" height="150"
                 src="@Url.Action("GetImage", "Images",
                            new {imageId = Model.ImageId })" />
        }
    </td>

    <td>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Details", "Details", new { id = Model.Id }) |
        @*@Html.ActionLink("Delete", "Delete", new { id = Model.Id })*@
        @using (Ajax.BeginForm("Delete", new { }, new AjaxOptions() { Confirm = "Удалить?", HttpMethod = "POST", OnSuccess = "OnNoteRemove", OnFailure = "OnError" }, new { style = "display: inline-block" }))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("Id", Model.Id)
            <input type="submit" value="Delete" class="btn btn-danger" />}
    </td>
</tr>

Rewarding/Rewarding/Views/Rewards/_rewardsListPartial.cshtml
@model IEnumerable<Rewarding.Models.Reward>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="rewardsListBody">
        @foreach (var item in Model)
        {
            {
                Html.RenderPartial("_rewardSinglePartial", item);
            }
        }
     </tbody>

</table>